export const state = {
  activePage: "simulation",
  railCollapsed: false,
  config: null,
  calibration: null,
  currentRun: null,
  currentRunId: null,
  comparison: null,
  comparisonMode: "baseline",
  comparisonMetric: "milk",
  selectedPeriod: "daily",
  parameterDraft: {},
  parameterErrors: {},
  parameterLoading: false,
  filters: {},
  view: "ledger",
  period: "daily",
  data: null,
  loading: false,
  error: null,
  warnings: [],
  cowSort: "milk_l",
};
